//
// File generated by /afs/cern.ch/cms/slc5_amd64_gcc462/lcg/root/5.32.00-cms21/bin/rootcint at Sun Dec  8 11:10:23 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIafsdIcerndOchdIworkdIsdIsigamanidIpublicdICMSSW_5_3_7_STOPdIsrcdIbabyReaderSTOPSdIrunAnalysisdIcalcFOM_C_ACLiC_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "calcFOM_C_ACLiC_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

/********************************************************
* /afs/cern.ch/work/s/sigamani/public/CMSSW_5_3_7_STOP/src/babyReaderSTOPS/runAnalysis/calcFOM_C_ACLiC_dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablecalcFOM_C_ACLiC_dict();

extern "C" void G__set_cpp_environmentcalcFOM_C_ACLiC_dict() {
  G__cpp_reset_tagtablecalcFOM_C_ACLiC_dict();
}
#include <new>
extern "C" int G__cpp_dllrevcalcFOM_C_ACLiC_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__calcFOM_C_ACLiC_dict__0_1905(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) calcSoSqrtB((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1906(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) maxbin((TH1D*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1907(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      outputBDTplots(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1908(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      makeAlloutputBDTplots(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1909(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) FOM(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1910(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      makeCLsCards(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1911(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      make2Dplot(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (int) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1912(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      make2Dplot_MAX(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1913(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      make2Dplot_MAX_OffShell(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (int) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1914(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      makeAllPlots();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__calcFOM_C_ACLiC_dict__0_1915(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      createTableCLs(
*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5])
, (double) G__double(libp->para[6]), (double) G__double(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunccalcFOM_C_ACLiC_dict {
 public:
  G__Sizep2memfunccalcFOM_C_ACLiC_dict(): p(&G__Sizep2memfunccalcFOM_C_ACLiC_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunccalcFOM_C_ACLiC_dict::*p)();
};

size_t G__get_sizep2memfunccalcFOM_C_ACLiC_dict()
{
  G__Sizep2memfunccalcFOM_C_ACLiC_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancecalcFOM_C_ACLiC_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablecalcFOM_C_ACLiC_dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__calcFOM_C_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarcalcFOM_C_ACLiC_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunccalcFOM_C_ACLiC_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
   G__memvar_setup((void*)(&f_syst),100,0,0,-1,-1,-1,1,"f_syst=",0,(char*)NULL);

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalcalcFOM_C_ACLiC_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
   G__memfunc_setup("calcSoSqrtB", 1089, G__calcFOM_C_ACLiC_dict__0_1905, 100, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - S d - - 0 - B", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("maxbin", 639, G__calcFOM_C_ACLiC_dict__0_1906, 105, -1, -1, 0, 1, 1, 1, 0, "U 'TH1D' - 0 - histo", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("outputBDTplots", 1469, G__calcFOM_C_ACLiC_dict__0_1907, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - setup u 'TString' - 0 - MVA "
"u 'TString' - 0 - dir i - - 0 - MSTOP "
"i - - 0 - MLSP", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("makeAlloutputBDTplots", 2164, G__calcFOM_C_ACLiC_dict__0_1908, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - setup u 'TString' - 0 - BDT "
"u 'TString' - 0 - dir", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("FOM", 226, G__calcFOM_C_ACLiC_dict__0_1909, 100, -1, -1, 0, 6, 1, 1, 0, 
"u 'TString' - 0 - setup u 'TString' - 0 - BDT "
"u 'TString' - 0 - dir i - - 0 - MSTOP "
"i - - 0 - MLSP i - - 0 - num", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("makeCLsCards", 1165, G__calcFOM_C_ACLiC_dict__0_1910, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - setup u 'TString' - 0 - BDT "
"u 'TString' - 0 - dir i - - 0 - MSTOP "
"i - - 0 - MLSP", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("make2Dplot", 979, G__calcFOM_C_ACLiC_dict__0_1911, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - dir u 'TString' - 0 - setup "
"u 'TString' - 0 - BDT i - - 0 - num", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("make2Dplot_MAX", 1304, G__calcFOM_C_ACLiC_dict__0_1912, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - setup u 'TString' - 0 - dir "
"i - - 0 - num", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("make2Dplot_MAX_OffShell", 2186, G__calcFOM_C_ACLiC_dict__0_1913, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - setup1 u 'TString' - 0 - setup2 "
"u 'TString' - 0 - dir i - - 0 - num", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("makeAllPlots", 1225, G__calcFOM_C_ACLiC_dict__0_1914, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("createTableCLs", 1374, G__calcFOM_C_ACLiC_dict__0_1915, 121, -1, -1, 0, 8, 1, 1, 0, 
"u 'TString' - 0 - setup u 'TString' - 0 - BDT "
"i - - 0 - S i - - 0 - N "
"d - - 0 - signal d - - 0 - ttbar "
"d - - 0 - wjets d - - 0 - others", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funccalcFOM_C_ACLiC_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablecalcFOM_C_ACLiC_dict() {
  G__calcFOM_C_ACLiC_dictLN_TString.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_TH1D.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__calcFOM_C_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablecalcFOM_C_ACLiC_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_TString);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__calcFOM_C_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
}
extern "C" void G__cpp_setupcalcFOM_C_ACLiC_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupcalcFOM_C_ACLiC_dict()");
  G__set_cpp_environmentcalcFOM_C_ACLiC_dict();
  G__cpp_setup_tagtablecalcFOM_C_ACLiC_dict();

  G__cpp_setup_inheritancecalcFOM_C_ACLiC_dict();

  G__cpp_setup_typetablecalcFOM_C_ACLiC_dict();

  G__cpp_setup_memvarcalcFOM_C_ACLiC_dict();

  G__cpp_setup_memfunccalcFOM_C_ACLiC_dict();
  G__cpp_setup_globalcalcFOM_C_ACLiC_dict();
  G__cpp_setup_funccalcFOM_C_ACLiC_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunccalcFOM_C_ACLiC_dict();
  return;
}
class G__cpp_setup_initcalcFOM_C_ACLiC_dict {
  public:
    G__cpp_setup_initcalcFOM_C_ACLiC_dict() { G__add_setup_func("calcFOM_C_ACLiC_dict",(G__incsetup)(&G__cpp_setupcalcFOM_C_ACLiC_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initcalcFOM_C_ACLiC_dict() { G__remove_setup_func("calcFOM_C_ACLiC_dict"); }
};
G__cpp_setup_initcalcFOM_C_ACLiC_dict G__cpp_setup_initializercalcFOM_C_ACLiC_dict;

