/********************************************************************
* /afs/cern.ch/work/s/sigamani/public/CMSSW_5_3_7_STOP/src/babyReaderSTOPS/runAnalysis/calcFOM_C_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/cern.ch/work/s/sigamani/public/CMSSW_5_3_7_STOP/src/babyReaderSTOPS/runAnalysis/calcFOM_C_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecalcFOM_C_ACLiC_dict();
extern void G__cpp_setup_inheritancecalcFOM_C_ACLiC_dict();
extern void G__cpp_setup_typetablecalcFOM_C_ACLiC_dict();
extern void G__cpp_setup_memvarcalcFOM_C_ACLiC_dict();
extern void G__cpp_setup_globalcalcFOM_C_ACLiC_dict();
extern void G__cpp_setup_memfunccalcFOM_C_ACLiC_dict();
extern void G__cpp_setup_funccalcFOM_C_ACLiC_dict();
extern void G__set_cpp_environmentcalcFOM_C_ACLiC_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/afs/cern.ch/work/s/sigamani/public/CMSSW_5_3_7_STOP/src/babyReaderSTOPS/runAnalysis/./calcFOM.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TString;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TH1D;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__calcFOM_C_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;

/* STUB derived class for protected member access */
