// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/afs/cern.ch/work/s/sigamani/public/CMSSW_5_3_7_STOP/src/babyReaderSTOPS/runAnalysis/./calcFOM.C";

#endif
